### ISSUE TITLE
关于iOS原型设计的想法

### ISSUE THREAD

**Issue by imcj** [imcj/caas#1]
之前我写的原型在iOS内如何实现？ @heji 下面的代码是我设计的原型。

比如点符号访问对象属性可以在第一版实现，[]进行数组访问，其他的比如变量的支持可以以后再考虑。

你现在在README里写的是代码实现了。你能明白我在说什么吗？

```Objective-C
/**
 * 第二个参数是默认值
 */
(void *)get(NSString *key, ...);
(int)getInt(NSString *key, ...);
(float)getFloat(NSString *key, ...);
(NSString)getString(NSString *key, ...);

get("system.site.name")
// will print http://example.com

get("ui.homepage.font_size", 12);
// 如果不存在，将返回12

get("ui.homepage.banner[0].image_url")
// [index] 

get("ui.homepage.banner[last]") 

get("ui.homepage.banner[-2]")

get("current.sitename", "shmg");

get("site.${current.sitename}.articles)

get("sites[@site.name=SHMG]", "shmg");
// current.sitename 作为变量访问指定的site的属性名

```

**Comment by songtao046** [comment]
是要写提供了什么功能，能够做些什么事情吗？

**Comment by imcj** [comment]
两件事情，第一件事是我们自己弄明白这是什么。然后是让别人弄明白这能做什么。
Songtao <notifications@github.com>于2016年12月31日 周六下午8:33写道：

**Comment by imcj** [comment]
@songtao046 你看到这个原型了吗，可以定义一个get的宏。

**Comment by songtao046** [comment]
这个要研究一下，之前没接触过这类写法

**Comment by imcj** [comment]
你说没有接触过的是宏macro?
Songtao <notifications@github.com>于2016年12月31日 周六下午8:56写道：

**Comment by songtao046** [comment]
我说符号访问那个

**Comment by imcj** [comment]
目前只需要支持点符号访问和数组索引就可以了。这些写法是我参考了xpath和css selector的。

Songtao <notifications@github.com>于2016年12月31日 周六下午9:01写道：

**Comment by imcj** [comment]
甚至是直接使用oc的keypath，数组都不用支持。先建立项目，把一些简单的功能先实现。

比如
- 从网络抓取json文件
- 支持cocoapod
- 缓存到本地
- 从服务器主动推动更新

@songtao046
